apiVersion: apps/v1
kind: Deployment
metadata:
    name: amazee-asessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata: 
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: amazee-app1
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - backend:
              serviceName: app1
              servicePort: 3000